### ISSUE TITLE
Search crashes when typing too fast

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-android#531]
The app crashes on my phone when typing too fast in the search bar (Pixel XL, Android 8.1)

Repro:

1. Build from `develop`
2. Open search
3. Start typing very fast (I repro'd typing `daniele` but I don't think it matters) 
4. Observe the app crashing:

```
java.lang.IndexOutOfBoundsException: Index: 52, Size: 11
    at java.util.ArrayList.get(ArrayList.java:437)
    at net.squanchy.search.view.GridSpanSizeLookup.getSpanSize(GridSpanSizeLookup.kt:13)
    at android.support.v7.widget.GridLayoutManager$SpanSizeLookup.getSpanGroupIndex(GridLayoutManager.java:971)
    at android.support.v7.widget.GridLayoutManager.getSpanGroupIndex(GridLayoutManager.java:451)
    at android.support.v7.widget.GridLayoutManager.getRowCountForAccessibility(GridLayoutManager.java:125)
    at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:9991)
    at android.support.v7.widget.RecyclerView$LayoutManager.onInitializeAccessibilityNodeInfo(RecyclerView.java:9951)
    at android.support.v7.widget.RecyclerViewAccessibilityDelegate.onInitializeAccessibilityNodeInfo(RecyclerViewAccessibilityDelegate.java:61)
    at android.support.v4.view.AccessibilityDelegateCompat$AccessibilityDelegateApi16Impl$1.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:126)
    at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7343)
    at android.view.View.createAccessibilityNodeInfoInternal(View.java:7304)
    at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:26062)
    at android.view.View.createAccessibilityNodeInfo(View.java:7287)
    at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1147)
    at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:972)
    at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:336)
    at android.view.AccessibilityInteractionController.-wrap1(Unknown Source:0)
    at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1324)
    …
```

**Comment by rock3r** [comment]
The issue was unfortunately not fixed
